# Generated by Django 5.0.4 on 2024-06-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_guardian_orphan_guardian_orphans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='address',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
