# Generated by Django 5.0.4 on 2024-06-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_guardian_address_alter_guardian_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphan',
            name='details',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
